name: Test and lint PR

on: pull_request

jobs:
  test_and_lint:
    name: Run the tests and linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies 📦
        run: npm install
      - name: Run the tests 🧪
        run: npm test
      - name: Lint the codebase ✅
        run: npm run lint
