name: Publish website

on:
  - workflow_dispatch
  - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout time!
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: cd www
      - name: Install and build
        run: |
          npm ci
          npm run build
      - name: Deploy to GitHub Pages!
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
